### ISSUE TITLE
Is package still in active development

### ISSUE THREAD

**Issue by merlindiavova** [auraphp/Aura.Di#166]
Hi,

Just a quick question to find if this package is still in active development. I have been using it for a while and it seems dev has stopped. Just wanted some clarification.

Thanks

**Comment by djmattyg007** [comment]
I believe all Aura PHP packages should be considered "under active development", even if they aren't being regularly worked on. As another user of various Aura PHP packages, I have confidence that they would receive timely security fixes should the need arise. Otherwise, I'm glad to be using a stable and reliable piece of software that appears to have largely reached feature-completeness. Of course I can't speak for @pmjones, @harikt, etc, but I suspect the appearance of a lack of development simply comes from there being no desire for new features to be added.

**Comment by merlindiavova** [comment]
Thanks @djmattyg007, yeah I largely feel the same way but as I'm going to be putting some auraphp packages in production I wanted  some clarification.

**Comment by harikt** [comment]
I am not currently working on anything with Aura. So I don't need any features or have found bugs. But I have tried to push things to releases when ever I noticed some major features or bugs are found in my available time. Sometimes I can't merge my own PR or complicated PR's from others for my incompetence. So it may take some time depending on the availability of Paul himself.

I can't speak for tomorrow. But I hope we all will be here to fix bugs and push next releases or we can add more people to team to move things. I also don't stop you from using anything outside aura. The risk of using someones code is at somepoint of time you should be willing to maintain that piece. If it is less, you have less to maintain ;) .

**Comment by frederikbosch** [comment]
This can be closed due to the merge of #173.
