### ISSUE TITLE
Question: How to make values available in multiple Container configs?

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Di#198]
I have a configuration file that my application only reads once.  I've done this in a `ContainerConfig::define()` child class (e.g. `MyAppCommon`), and stored the values using `$di->["keyname"] = <config value>;`.  This has worked fine for injecting those values into all of the objects where needed -- until now.

I'm using multiple containers in my `ContainerBuilder` call, much like this:
```php
$container_builder = new ContainerBuilder();

$di = $container_builder->newConfiguredInstance([
    'MyClass1',
    'MyAppCommon',
    'MyClass2',
]);
```
The config file is read in the `MyAppCommon` container configuration.  If I try to _use_ those values in the `MyClass2` container configuration, it works.  But if I try to use them in the `MyClass1` container configuration, they are undefined.  Clearly, the order of the above array parameter matters.  

Should it?  Maybe this is inappropriate use of the `$di->values` array.

What's the correct way to accomplish what I'm trying to do?

**Comment by far-blue** [comment]
I know it's a while since this issue was raised but in case it's still helpful I thought I'd cover the 2 approaches I've used.

The first time I ran into this I was doing the same as you - basically 'consuming' the config file in the ContainerConfig. I ended up having a ContainerConfig class that I placed first in the set and which did nothing but consume the config into various values I could then use in later ContainerConfigs.

However, in time I've found that approach is too closely coupled to make it easy to reuse ContainerConfigs. So these days I first parse the config into an array structure or similar and then pass either the entire config array or a sub-section of the array into the ContainerConfig class instances as a constructor parameter (along with which environment I'm running in - dev, uat, production etc.). This allows me to write re-usable ContainerConfigs for things like db and logging. In the config file, for instance, the section to do with logging then simply needs to be in the structure expected by the logging ContainerConfig (and so on with other sections and their ContainerConfigs) rather than having to match up named keys for everything in the config file for every project.

**Comment by cxj** [comment]
Ah, how do you pass the array to those `ContainerConfig` class instances?  Maybe I'm just having a total brain error here, but if I'm passing string names of classes to `ContainerBuilder`, I don't see a way to pass an argument.

**Comment by far-blue** [comment]
Right, yeah, you have to instantiate instances of the ContainerConfig classes, passing parameters to the constructor, then hand those instances rather than the string class names in the array to ContainerBuilder. You can actually provide a mix of strings and class instances if wanted.

**Comment by harikt** [comment]
Hey @cxj ,

I know it is late, were you able to fix this and move on ? 

If not what version of di are you using and do you still need help on this ? 

Else can we close it ?

**Comment by cxj** [comment]
Yeah, we can close it.  I'll do that.
