### ISSUE TITLE
Container-interop compatibility

### ISSUE THREAD

**Issue by mnapoli** [auraphp/Aura.Di#77]
Hi there!

I had a look at your `ContainerInterface` and it seems 100% compatible with the one in [container-interop](https://github.com/container-interop/container-interop). Would you consider implementing it?

Cheers!

**Comment by harikt** [comment]
:) . I don't know, but I know some answers though ;) .

Thank you.

**Comment by pmjones** [comment]
Hi @mnapoli -- I like the container-interop project. My problem, though, is that one of the Aura goals is that its library packages have no dependencies. Now, I think it might be reasonable to say that "an interface is not a dependency" but then I'll have to field endless defenses of that position. So that answer, for now, has to be "no," at least until we either modify the marketing language or the project goals.

**Comment by mnapoli** [comment]
Ha I see the problem ;)

Thanks for the answer!

**Comment by harikt** [comment]
@pmjones then may be time to modify the marketing language :) . And you know I am looking especially at the thread https://groups.google.com/d/msg/auraphp/dVpSOV6RnM4/HWynJROLm-gJ
