### ISSUE TITLE
property-read designation causes PHPStorm to have syntax error

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Di#91]
PHPStorm 9 reports that the @property-read designation on the DI properties (params, etc) to be a syntax error.

**Comment by pmjones** [comment]
Is this an issue with Aura.Di, or with PHPStorm 9? My understanding is that earlier versions of PHPStorm recognized it.

**Comment by brandonsavage** [comment]
If the property designation is wrong (since it's actually NOT a read-only
property) it's an error with Aura.Di.

**Comment by pmjones** [comment]
Gotcha. PRs welcome on this one, since I don't use PHPStorm and thus can't test it.

**Comment by silentworks** [comment]
@brandonsavage I am using PHPStorm 9, I don't have this issue at all, so it might just be that you need to invalidate your cache and restart PHPStorm.

**Comment by brandonsavage** [comment]
That doesn't solve the issue. I think Aura.Di 3.x doesn't use the setting.

**Comment by pmjones** [comment]
@brandonsavage If you can submit a PR that fixes the issue, I'll be happy to review it.

**Comment by brandonsavage** [comment]
Done.

**Comment by harikt** [comment]
Hi @brandonsavage , 

Is this issue for 2.x or 3.x? From your comment https://github.com/auraphp/Aura.Di/issues/91#issuecomment-126123160 it seems the issue with 3.x as @silentworks doesn't face the same. And PR #93  is on 2.x branch when I checked to merge.

Thank you.

**Comment by silentworks** [comment]
This is for 3.x, I have now noticed the issue too. Sorry I should have clarified that I am also using 3.x.

**Comment by brandonsavage** [comment]
My patch is for 2.x, though I'm sure it can be ported and applied to 3.x.
I'm using 2.x

**Comment by pmjones** [comment]
I've opened the 2.x Container file in PHPStorm 9.0.1, and I don't notice it reporting a syntax error. Am I missing something?

![screen shot 2015-08-17 at 01 08 41](https://cloud.githubusercontent.com/assets/25754/9298988/ae677504-447c-11e5-80a7-01df654d1979.png)

**Comment by silentworks** [comment]
There is no issue by opening the file directly, but if you try to set `$container->types['']` that is where the issue is, as in the docblocks of the class it states it is a read only property although in the Aura.Di documentation it states you can write to it.

I think these properties should be actual methods in Container rather than using the magical `__get` to set them.

Also note, this is the same in the 3.x branch, I am currently just ignoring the error even though it exists.

Screenshot of error example below:

<img width="988" alt="screenshot 2015-08-17 08 57 18" src="https://cloud.githubusercontent.com/assets/79497/9300459/1669b856-44be-11e5-8b0a-792a6b27d106.png">

**Comment by pmjones** [comment]
> if you try to set $container->types[''] that is where the issue is

Gotcha.

> I think these properties should be actual methods in Container rather than using the magical __get to set them.

Let me see what I can do.
